"""Hallucination evaluator — the full pipeline.

Ties together:
1. Claim extraction (LLM-based)
2. NLI grounding scoring (BART-MNLI)
3. Confidence aggregation

Usage:
    evaluator = HallucinationEvaluator()
    report = evaluator.evaluate(
        generated_text="LLMs use attention mechanisms...",
        evidence_chunks=[{"text": "...", "source": "paper.pdf"}],
    )
    print(report.overall_confidence)
    print(report.claim_results)
"""

import time

from atlas.evaluator.confidence import ConfidenceScorer, EvaluationReport
from atlas.evaluator.grounding import GroundingScorer
from atlas.evaluator.hallucination import ClaimExtractor
from atlas.observability.logger import get_logger
from atlas.observability.tracer import StepType, Trace, TraceStep

log = get_logger(__name__)


class HallucinationEvaluator:
    """End-to-end hallucination detection pipeline.

    1. Extract atomic claims from the generated text
    2. Score each claim against retrieved evidence using NLI
    3. Aggregate into an overall confidence score
    """

    def __init__(
        self,
        support_threshold: float = 0.5,
        nli_model: str = "facebook/bart-large-mnli",
    ):
        """
        Args:
            support_threshold: Min entailment score to count as supported.
            nli_model: HuggingFace model for NLI scoring.
        """
        self._extractor = ClaimExtractor()
        self._scorer = GroundingScorer(model_name=nli_model)
        self._confidence = ConfidenceScorer(support_threshold=support_threshold)

        log.info("hallucination_evaluator_ready")

    def evaluate(
        self,
        generated_text: str,
        evidence_chunks: list[dict],
        trace: Trace | None = None,
    ) -> EvaluationReport:
        """Run the full hallucination detection pipeline.

        Args:
            generated_text: The text generated by the agent.
            evidence_chunks: Retrieved evidence. Each dict needs
                             'text' and 'source' keys.
            trace: Optional trace for observability.

        Returns:
            EvaluationReport with per-claim scores and overall confidence.
        """
        start_time = time.time()

        # Step 1: Extract claims
        log.info("extracting_claims", text_length=len(generated_text))
        claims = self._extractor.extract(generated_text)

        if not claims:
            log.warning("no_claims_extracted")
            return EvaluationReport()

        log.info("claims_extracted", num_claims=len(claims))

        # Step 2: Score each claim against evidence
        log.info(
            "scoring_claims",
            num_claims=len(claims),
            num_evidence=len(evidence_chunks),
        )
        grounding_results = self._scorer.score_claims(claims, evidence_chunks)

        # Step 3: Aggregate into confidence score
        report = self._confidence.evaluate(grounding_results)

        end_time = time.time()
        latency = round((end_time - start_time) * 1000, 2)

        log.info(
            "hallucination_evaluation_complete",
            total_claims=report.total_claims,
            supported=report.supported_claims,
            unsupported=report.unsupported_claims,
            contradicted=report.contradicted_claims,
            confidence=report.overall_confidence,
            latency_ms=latency,
        )

        # Add to trace if provided
        if trace:
            trace.add_step(
                TraceStep(
                    step_id="hallucination_eval",
                    step_type=StepType.EVALUATION,
                    input_data={
                        "num_claims": len(claims),
                        "num_evidence": len(evidence_chunks),
                    },
                    output_data=report.to_dict(),
                    start_time=start_time,
                    end_time=end_time,
                )
            )

        return report
