"""Tests for citation manager and report generator."""

from atlas.evaluator.confidence import EvaluationReport
from atlas.report.citations import CitationManager
from atlas.report.generator import ReportGenerator


class TestCitationManager:
    """Test citation tracking and formatting."""

    def test_add_source(self):
        mgr = CitationManager()
        c = mgr.add_source("paper.pdf", title="Some Paper")
        assert c.number == 1
        assert c.source == "paper.pdf"
        assert mgr.num_citations == 1

    def test_duplicate_source_reuses_citation(self):
        mgr = CitationManager()
        c1 = mgr.add_source("paper.pdf")
        c2 = mgr.add_source("paper.pdf")
        assert c1.number == c2.number
        assert mgr.num_citations == 1

    def test_multiple_sources_increment(self):
        mgr = CitationManager()
        c1 = mgr.add_source("source_a")
        c2 = mgr.add_source("source_b")
        c3 = mgr.add_source("source_c")
        assert c1.number == 1
        assert c2.number == 2
        assert c3.number == 3

    def test_format_inline(self):
        mgr = CitationManager()
        c = mgr.add_source("paper.pdf")
        assert c.format_inline() == "[1]"

    def test_format_bibliography(self):
        mgr = CitationManager()
        mgr.add_source("paper.pdf", title="ML Paper")
        mgr.add_source("arxiv:1234", title="Arxiv Paper")

        bib = mgr.format_bibliography()
        assert "## References" in bib
        assert "[1]" in bib
        assert "[2]" in bib
        assert "ML Paper" in bib

    def test_empty_bibliography(self):
        mgr = CitationManager()
        assert mgr.format_bibliography() == ""

    def test_to_list(self):
        mgr = CitationManager()
        mgr.add_source("s1", title="Title 1")
        mgr.add_source("s2", title="Title 2")

        result = mgr.to_list()
        assert len(result) == 2
        assert result[0]["number"] == 1
        assert result[1]["title"] == "Title 2"


class TestReportGenerator:
    """Test report generation."""

    def test_basic_report(self):
        gen = ReportGenerator()
        report = gen.generate(
            query="What is BERT?",
            answer="BERT is a bidirectional language model.",
            sources=[],
        )

        assert "# ATLAS Research Report" in report
        assert "What is BERT?" in report
        assert "BERT is a bidirectional language model." in report
        assert "Generated by ATLAS" in report

    def test_report_with_evaluation(self):
        gen = ReportGenerator()
        evaluation = EvaluationReport(
            total_claims=3,
            supported_claims=2,
            unsupported_claims=1,
            contradicted_claims=0,
            overall_confidence=0.6667,
            claim_results=[
                {
                    "claim": "BERT uses attention",
                    "status": "supported",
                    "score": 0.95,
                    "label": "entailment",
                    "evidence_source": "paper.pdf",
                    "evidence_preview": "evidence text",
                },
                {
                    "claim": "BERT was made in 2018",
                    "status": "supported",
                    "score": 0.88,
                    "label": "entailment",
                    "evidence_source": "paper.pdf",
                    "evidence_preview": "evidence text",
                },
                {
                    "claim": "BERT has 1T params",
                    "status": "unsupported",
                    "score": 0.3,
                    "label": "neutral",
                    "evidence_source": "paper.pdf",
                    "evidence_preview": "evidence text",
                },
            ],
        )

        report = gen.generate(
            query="Tell me about BERT",
            answer="BERT is great.",
            sources=[],
            evaluation=evaluation,
        )

        assert "Confidence" in report
        assert "67%" in report
        assert "Grounding Analysis" in report
        assert "✅" in report
        assert "⚠️" in report
        assert "SUPPORTED" in report
        assert "UNSUPPORTED" in report

    def test_report_with_sources(self):
        gen = ReportGenerator()
        sources = [
            {
                "tool": "arxiv_search",
                "query": "BERT model",
                "result_preview": "BERT paper abstract...",
            },
            {
                "tool": "web_search",
                "query": "BERT Google",
                "result_preview": "Google released BERT...",
            },
        ]

        report = gen.generate(
            query="What is BERT?",
            answer="BERT is a model.",
            sources=sources,
        )

        assert "References" in report
        assert "arxiv_search" in report

    def test_report_with_dag_summary(self):
        gen = ReportGenerator()
        dag_summary = {
            "num_tasks": 3,
            "completed": 3,
            "pending": 0,
            "failed": 0,
            "tasks": [
                {"query": "What is BERT?", "status": "completed"},
                {"query": "What is GPT?", "status": "completed"},
                {"query": "Compare them", "status": "completed"},
            ],
        }

        report = gen.generate(
            query="Compare BERT and GPT",
            answer="They differ in architecture.",
            sources=[],
            dag_summary=dag_summary,
        )

        assert "Research Process" in report
        assert "3 sub-tasks" in report
        assert "What is BERT?" in report
